site_name: LeapDAO
theme: readthedocs

nav:
  - 'Home': index.md
  - 'How to use': how-to-use.md
  - 'Spending Conditions': spending-conditions.md
  - 'Deploying Spending Conditions': spending-conditions-tutorial.md
  - 'Connect to testnet': connect.md
  - 'JSON RPC':
    - 'Overview': json-rpc/overview.md
    - 'web3.eth': json-rpc/web3.eth.md
    - 'web3.net': json-rpc/web3.net.md
    - 'Leap web3 extension': json-rpc/web3.plasma.md
  - 'Recipes':
    - 'Use Web3': 'recipes/use-web3.md'
    - 'Use your own token': 'recipes/own-token.md'
    - 'Transfer tokens': 'recipes/send-transfer.md'
  - 'Advanced':
    - 'Data structures': data-structures.md
